name: jasonharms
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#26292e'
    - '#000000'
    - '#c9b682'
    - '#46575e'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
