name: jasonharms
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#26292e'
    - '#000000'
    - '#c9b682'
    - '#46575e'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
