name: jasonharms
favicon: null
layout_spectrum: 0.00371
typography_spectrum: 0.36275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfafb'
    - '#878f83'
    - '#000000'
    - '#cd6728'
    - '#d2bea8'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
