name: jasonharms
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#dedede'
    - '#535353'
    - '#000000'
    - '#909090'
  brandStrength: 0.875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
